#ifndef ERRORS_H
#define ERRORS_H

#include <stdio.h>

typedef enum {
    ERROR_NONE,
    ERROR_INVALID_LOGIN,
    ERROR_INVALID_PIN,
    ERROR_USER_ALREADY_EXISTS,
    ERROR_USER_NOT_EXIST,
    ERROR_AUTH_FAILED,
    ERROR_INVALID_COMMAND,
    ERROR_INVALID_TIME_FORMAT,
    ERROR_INVALID_FLAG,
    ERROR_INVALID_REQUEST_LIMIT,
    ERROR_SANCTION_CONFIRMATION_FAILED,
    ERROR_MEMORY_ALLOCATION,
    ERROR_USER_NOT_FOUND,
    ERROR_TOO_MANY_REQUESTS,
    ERROR_INVALID_INPUT,
    ERROR_OPEN_FILE_FAILED,
    ERROR_WRITE_TO_FILE_FAILED,
    ERROR_FAILED_TO_GET_TIME,
} Error;

void LogErrors(Error);
const char *ErrorToString(const Error);

#endif